package com.incode.welcome_sdk.ui.id_capture.view;

import androidx.compose.ui.graphics.ImageBitmap;
import androidx.compose.ui.tooling.preview.PreviewParameterProvider;
import com.incode.welcome_sdk.commons.CloseButtonPosition;
import com.incode.welcome_sdk.commons.HelpButtonPosition;
import com.incode.welcome_sdk.ui.camera.id_validation.base.DocumentType;
import com.incode.welcome_sdk.ui.id_capture.AcceptedDocumentsUiState;
import com.incode.welcome_sdk.ui.id_capture.AnalyzingDocumentModel;
import com.incode.welcome_sdk.ui.id_capture.CaptureUiState;
import com.incode.welcome_sdk.ui.id_capture.IconTintType;
import com.incode.welcome_sdk.ui.id_capture.IdCapturePresentableError;
import com.incode.welcome_sdk.ui.id_capture.InfoModel;
import com.incode.welcome_sdk.ui.id_capture.StatusColor;
import com.incode.welcome_sdk.ui.id_capture.SuggestionBoxModel;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.sequences.Sequence;
import kotlin.sequences.SequencesKt;

/* JADX INFO: loaded from: classes5.dex */
final class c implements PreviewParameterProvider<CaptureUiState> {

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    private static int f15690b = 1;

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    private static int f15691c = 0;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    private final Sequence<CaptureUiState> f15692a;

    public c() {
        boolean z2 = false;
        boolean z3 = false;
        boolean z4 = false;
        boolean z5 = false;
        boolean z6 = false;
        boolean z7 = false;
        boolean z8 = false;
        boolean z9 = false;
        byte b2 = 0 == true ? 1 : 0;
        byte b3 = 0 == true ? 1 : 0;
        byte b4 = 0 == true ? 1 : 0;
        byte b5 = 0 == true ? 1 : 0;
        byte b6 = 0 == true ? 1 : 0;
        byte b7 = 0 == true ? 1 : 0;
        int i2 = 67108863;
        DefaultConstructorMarker defaultConstructorMarker = null;
        boolean z10 = false;
        SuggestionBoxModel suggestionBoxModel = null;
        InfoModel infoModel = null;
        AnalyzingDocumentModel analyzingDocumentModel = null;
        boolean z11 = false;
        boolean z12 = false;
        CaptureUiState.CaptureFrameSpec captureFrameSpec = null;
        StatusColor statusColor = null;
        boolean z13 = false;
        ImageBitmap imageBitmap = null;
        ImageBitmap imageBitmap2 = null;
        boolean z14 = false;
        boolean z15 = false;
        boolean z16 = false;
        Integer num = null;
        boolean z17 = false;
        CaptureUiState.BottomButton bottomButton = null;
        boolean z18 = false;
        boolean z19 = false;
        boolean z20 = false;
        boolean z21 = false;
        IconTintType iconTintType = null;
        boolean z22 = false;
        AcceptedDocumentsUiState acceptedDocumentsUiState = null;
        CloseButtonPosition closeButtonPosition = null;
        HelpButtonPosition helpButtonPosition = null;
        AnalyzingDocumentModel analyzingDocumentModel2 = null;
        boolean z23 = false;
        CaptureUiState.Companion companion = CaptureUiState.f14575e;
        int i3 = 67108863;
        DefaultConstructorMarker defaultConstructorMarker2 = null;
        InfoModel infoModel2 = null;
        boolean z24 = false;
        boolean z25 = false;
        CaptureUiState.CaptureFrameSpec captureFrameSpec2 = null;
        boolean z26 = false;
        ImageBitmap imageBitmap3 = null;
        boolean z27 = false;
        CaptureUiState.BottomButton bottomButton2 = null;
        boolean z28 = false;
        boolean z29 = false;
        CloseButtonPosition closeButtonPosition2 = null;
        byte b8 = 0 == true ? 1 : 0;
        byte b9 = 0 == true ? 1 : 0;
        byte b10 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion2 = CaptureUiState.f14575e;
        ImageBitmap imageBitmap4 = null;
        byte b11 = 0 == true ? 1 : 0;
        byte b12 = 0 == true ? 1 : 0;
        byte b13 = 0 == true ? 1 : 0;
        byte b14 = 0 == true ? 1 : 0;
        byte b15 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion3 = CaptureUiState.f14575e;
        byte b16 = 0 == true ? 1 : 0;
        byte b17 = 0 == true ? 1 : 0;
        byte b18 = 0 == true ? 1 : 0;
        byte b19 = 0 == true ? 1 : 0;
        byte b20 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion4 = CaptureUiState.f14575e;
        byte b21 = 0 == true ? 1 : 0;
        byte b22 = 0 == true ? 1 : 0;
        byte b23 = 0 == true ? 1 : 0;
        byte b24 = 0 == true ? 1 : 0;
        byte b25 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion5 = CaptureUiState.f14575e;
        byte b26 = 0 == true ? 1 : 0;
        byte b27 = 0 == true ? 1 : 0;
        byte b28 = 0 == true ? 1 : 0;
        boolean z30 = false;
        boolean z31 = false;
        boolean z32 = false;
        byte b29 = 0 == true ? 1 : 0;
        byte b30 = 0 == true ? 1 : 0;
        byte b31 = 0 == true ? 1 : 0;
        byte b32 = 0 == true ? 1 : 0;
        byte b33 = 0 == true ? 1 : 0;
        byte b34 = 0 == true ? 1 : 0;
        int i4 = 67108863;
        SuggestionBoxModel suggestionBoxModel2 = null;
        boolean z33 = false;
        CaptureUiState.CaptureFrameSpec captureFrameSpec3 = null;
        boolean z34 = false;
        boolean z35 = false;
        Integer num2 = null;
        boolean z36 = false;
        boolean z37 = false;
        IconTintType iconTintType2 = null;
        boolean z38 = false;
        byte b35 = 0 == true ? 1 : 0;
        byte b36 = 0 == true ? 1 : 0;
        byte b37 = 0 == true ? 1 : 0;
        byte b38 = 0 == true ? 1 : 0;
        byte b39 = 0 == true ? 1 : 0;
        byte b40 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion6 = CaptureUiState.f14575e;
        boolean z39 = false;
        byte b41 = 0 == true ? 1 : 0;
        byte b42 = 0 == true ? 1 : 0;
        byte b43 = 0 == true ? 1 : 0;
        byte b44 = 0 == true ? 1 : 0;
        byte b45 = 0 == true ? 1 : 0;
        byte b46 = 0 == true ? 1 : 0;
        byte b47 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion7 = CaptureUiState.f14575e;
        byte b48 = 0 == true ? 1 : 0;
        byte b49 = 0 == true ? 1 : 0;
        byte b50 = 0 == true ? 1 : 0;
        byte b51 = 0 == true ? 1 : 0;
        byte b52 = 0 == true ? 1 : 0;
        byte b53 = 0 == true ? 1 : 0;
        byte b54 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion8 = CaptureUiState.f14575e;
        int i5 = 67108863;
        DefaultConstructorMarker defaultConstructorMarker3 = null;
        CaptureUiState.CaptureFrameSpec captureFrameSpec4 = null;
        boolean z40 = false;
        ImageBitmap imageBitmap5 = null;
        ImageBitmap imageBitmap6 = null;
        boolean z41 = false;
        CaptureUiState.BottomButton bottomButton3 = null;
        boolean z42 = false;
        boolean z43 = false;
        CloseButtonPosition closeButtonPosition3 = null;
        byte b55 = 0 == true ? 1 : 0;
        byte b56 = 0 == true ? 1 : 0;
        byte b57 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion9 = CaptureUiState.f14575e;
        byte b58 = 0 == true ? 1 : 0;
        byte b59 = 0 == true ? 1 : 0;
        byte b60 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion10 = CaptureUiState.f14575e;
        CaptureUiState captureUiStateChangeDocumentType = companion10.ChangeDocumentType(new CaptureUiState(false, 0 == true ? 1 : 0, null, null, false, false, captureFrameSpec4, 0 == true ? 1 : 0, z40, imageBitmap5, imageBitmap6, z31, z41, z36, 0 == true ? 1 : 0, z37, bottomButton3, z32, z8, z42, z38, 0 == true ? 1 : 0, z43, 0 == true ? 1 : 0, closeButtonPosition3, 0 == true ? 1 : 0, i5, defaultConstructorMarker3), DocumentType.PASSPORT);
        StatusColor statusColor2 = null;
        boolean z44 = false;
        CaptureUiState.Companion companion11 = CaptureUiState.f14575e;
        int i6 = 67108863;
        boolean z45 = false;
        ImageBitmap imageBitmap7 = null;
        boolean z46 = false;
        boolean z47 = false;
        Integer num3 = null;
        boolean z48 = false;
        IconTintType iconTintType3 = null;
        CloseButtonPosition closeButtonPosition4 = null;
        byte b61 = 0 == true ? 1 : 0;
        byte b62 = 0 == true ? 1 : 0;
        byte b63 = 0 == true ? 1 : 0;
        CaptureUiState.Companion companion12 = CaptureUiState.f14575e;
        this.f15692a = SequencesKt.sequenceOf(new CaptureUiState(false, null, null, null, false, false, null, null, false, null, null, false, false, false, null, z2, null, z3, false, z4, z5, null, z6, null, null, null, 67108863, null), CaptureUiState.f14575e.HelpScreen(new CaptureUiState(false, b3, null, null, false, false, null, b4, false, null, null, z7, z7, z2, b5, z3, null, z4, z5, z8, z6, b6, z9, b7, null, b2, 67108863, null)), CaptureUiState.Companion.TakePhotoManually$default(CaptureUiState.f14575e, new CaptureUiState(z10, suggestionBoxModel, infoModel, analyzingDocumentModel, z11, z12, captureFrameSpec, statusColor, z13, imageBitmap, imageBitmap2, z14, z15, z16, num, z17, bottomButton, z18, z19, z20, z21, iconTintType, z22, acceptedDocumentsUiState, closeButtonPosition, helpButtonPosition, i2, defaultConstructorMarker), null, false, false, 7, null), CaptureUiState.f14575e.ErrorFillTheFrame(new CaptureUiState(z10, suggestionBoxModel, infoModel, analyzingDocumentModel, z11, z12, captureFrameSpec, statusColor, z13, imageBitmap, imageBitmap2, z14, z15, z16, num, z17, bottomButton, z18, z19, z20, z21, iconTintType, z22, acceptedDocumentsUiState, closeButtonPosition, helpButtonPosition, i2, defaultConstructorMarker), false), companion.ErrorMisalignedId(new CaptureUiState(z23, null, infoModel2, analyzingDocumentModel2, z24, z25, captureFrameSpec2, 0 == true ? 1 : 0, z26, imageBitmap3, imageBitmap3, z2, z27, z3, 0 == true ? 1 : 0, z4, bottomButton2, z8, z6, z28, z9, b9, z29, b8, closeButtonPosition2, b10, i3, defaultConstructorMarker2)), companion2.ErrorBlurryId(new CaptureUiState(z23, 0 == true ? 1 : 0, infoModel2, analyzingDocumentModel2, z24, z25, captureFrameSpec2, b14, z26, imageBitmap4, imageBitmap3, z2, z27, z3, b15, z4, bottomButton2, z8, z6, z28, z9, b12, z29, b11, closeButtonPosition2, b13, i3, defaultConstructorMarker2)), companion3.ErrorGlareId(new CaptureUiState(z23, 0 == true ? 1 : 0, infoModel2, analyzingDocumentModel2, z24, z25, captureFrameSpec2, b19, z26, imageBitmap4, imageBitmap3, z2, z27, z3, b20, z4, bottomButton2, z8, z6, z28, z9, b17, z29, b16, closeButtonPosition2, b18, i3, defaultConstructorMarker2)), CaptureUiState.Companion.TakingPhoto$default(companion4, new CaptureUiState(z23, 0 == true ? 1 : 0, infoModel2, analyzingDocumentModel2, z24, z25, captureFrameSpec2, b24, z26, imageBitmap4, imageBitmap3, z2, z27, z3, b25, z4, bottomButton2, z8, z6, z28, z9, b22, z29, b21, closeButtonPosition2, b23, i3, defaultConstructorMarker2), null, 1, null), companion5.TakingPhoto(new CaptureUiState(z23, 0 == true ? 1 : 0, infoModel2, analyzingDocumentModel2, z24, z25, captureFrameSpec2, 0 == true ? 1 : 0, z26, imageBitmap4, imageBitmap3, z2, z27, z3, 0 == true ? 1 : 0, z4, bottomButton2, z8, z6, z28, z9, b27, z29, b26, closeButtonPosition2, b28, i3, defaultConstructorMarker2), 3), CaptureUiState.f14575e.TakingPhoto(new CaptureUiState(false, null, null, b34, z30, false, null, null, false, b32, null, z31, z31, z2, null, z3, b33, z4, z32, z8, z6, null, z9, b30, null, b29, 67108863, b31), 2), CaptureUiState.f14575e.TakingPhoto(new CaptureUiState(false, suggestionBoxModel2, b37, b38, z33, z30, captureFrameSpec3, b39, z34, null, b36, z35, z31, z31, num2, z36, null, z37, z4, z32, z8, iconTintType2, z38, null, b35, b40, i4, null), 1), companion6.TakingPhotoFlash(new CaptureUiState(z39, suggestionBoxModel2, b43, b44, z33, z30, captureFrameSpec3, b45, z34, 0 == true ? 1 : 0, b42, z35, z31, z31, num2, z36, 0 == true ? 1 : 0, z37, z4, z32, z8, iconTintType2, z38, 0 == true ? 1 : 0, b41, b46, i4, b47)), companion7.ShowTheBackOfYourId(new CaptureUiState(z39, suggestionBoxModel2, b50, b51, z33, z30, captureFrameSpec3, b52, z34, 0 == true ? 1 : 0, b49, z35, z31, z31, num2, z36, 0 == true ? 1 : 0, z37, z4, z32, z8, iconTintType2, z38, 0 == true ? 1 : 0, b48, b53, i4, b54)), CaptureUiState.Companion.AnalyzingDocument$default(companion8, new CaptureUiState(false, b55, null, null, false, false, captureFrameSpec4, 0 == true ? 1 : 0, z40, imageBitmap5, imageBitmap6, z31, z41, z36, 0 == true ? 1 : 0, z37, bottomButton3, z32, z8, z42, z38, 0 == true ? 1 : 0, z43, b56, closeButtonPosition3, b57, i5, defaultConstructorMarker3), 0.0f, null, false, false, 15, null), CaptureUiState.Companion.AnalyzingDocument$default(companion9, companion9.ChangeDocumentType(new CaptureUiState(false, b58, null, null, false, false, captureFrameSpec4, 0 == true ? 1 : 0, z40, imageBitmap5, imageBitmap6, z31, z41, z36, 0 == true ? 1 : 0, z37, bottomButton3, z32, z8, z42, z38, 0 == true ? 1 : 0, z43, b59, closeButtonPosition3, b60, i5, defaultConstructorMarker3), DocumentType.BACK_ID), 0.0f, null, false, false, 15, null), CaptureUiState.Companion.AnalyzingDocument$default(companion10, captureUiStateChangeDocumentType, 0.0f, null, false, false, 15, null), companion11.ErrorThereWasAProblem(CaptureUiState.Companion.AnalyzingDocument$default(companion11, new CaptureUiState(false, null, null, b61, z44, false, null, statusColor2, z45, 0 == true ? 1 : 0, imageBitmap7, z46, z47, z31, num3, z36, 0 == true ? 1 : 0, z37, z48, z32, z8, iconTintType3, z38, 0 == true ? 1 : 0, closeButtonPosition4, b62, i6, b63), 0.0f, null, false, false, 15, null), IdCapturePresentableError.f14783e.from(new IllegalStateException("")), CaptureUiState.CaptureFrameSpec.Companion.from$default(CaptureUiState.CaptureFrameSpec.f14613b, DocumentType.FRONT_ID, true, false, null, 12, null)), companion12.SuccessfullyProcessedContinue(CaptureUiState.Companion.AnalyzingDocument$default(companion12, new CaptureUiState(false, null, null, null, z44, false, null, statusColor2, z45, 0 == true ? 1 : 0, imageBitmap7, z46, z47, z31, num3, z36, 0 == true ? 1 : 0, z37, z48, z32, z8, iconTintType3, z38, 0 == true ? 1 : 0, closeButtonPosition4, 0 == true ? 1 : 0, i6, 0 == true ? 1 : 0), 0.0f, null, false, false, 15, null)));
    }

    public final Sequence<CaptureUiState> getValues() {
        int i2 = 2 % 2;
        int i3 = f15691c + 93;
        int i4 = i3 % 128;
        f15690b = i4;
        int i5 = i3 % 2;
        Sequence<CaptureUiState> sequence = this.f15692a;
        int i6 = i4 + 95;
        f15691c = i6 % 128;
        int i7 = i6 % 2;
        return sequence;
    }
}
