package com.google.android.gms.internal.mlkit_vision_object_detection_custom;

import com.drew.metadata.exif.makernotes.PanasonicMakernoteDirectory;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

/* JADX INFO: loaded from: classes8.dex */
final class zzht implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzht zza = new zzht();
    private static final FieldDescriptor zzaA;
    private static final FieldDescriptor zzaB;
    private static final FieldDescriptor zzaC;
    private static final FieldDescriptor zzaD;
    private static final FieldDescriptor zzaE;
    private static final FieldDescriptor zzaF;
    private static final FieldDescriptor zzaG;
    private static final FieldDescriptor zzaH;
    private static final FieldDescriptor zzaI;
    private static final FieldDescriptor zzaJ;
    private static final FieldDescriptor zzaK;
    private static final FieldDescriptor zzaL;
    private static final FieldDescriptor zzaM;
    private static final FieldDescriptor zzaN;
    private static final FieldDescriptor zzaO;
    private static final FieldDescriptor zzaP;
    private static final FieldDescriptor zzaQ;
    private static final FieldDescriptor zzaR;
    private static final FieldDescriptor zzaS;
    private static final FieldDescriptor zzaT;
    private static final FieldDescriptor zzaU;
    private static final FieldDescriptor zzaV;
    private static final FieldDescriptor zzaW;
    private static final FieldDescriptor zzaX;
    private static final FieldDescriptor zzaY;
    private static final FieldDescriptor zzaZ;
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzaz;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzba;
    private static final FieldDescriptor zzbb;
    private static final FieldDescriptor zzbc;
    private static final FieldDescriptor zzbd;
    private static final FieldDescriptor zzbe;
    private static final FieldDescriptor zzbf;
    private static final FieldDescriptor zzbg;
    private static final FieldDescriptor zzbh;
    private static final FieldDescriptor zzbi;
    private static final FieldDescriptor zzbj;
    private static final FieldDescriptor zzbk;
    private static final FieldDescriptor zzbl;
    private static final FieldDescriptor zzbm;
    private static final FieldDescriptor zzbn;
    private static final FieldDescriptor zzbo;
    private static final FieldDescriptor zzbp;
    private static final FieldDescriptor zzbq;
    private static final FieldDescriptor zzbr;
    private static final FieldDescriptor zzbs;
    private static final FieldDescriptor zzbt;
    private static final FieldDescriptor zzbu;
    private static final FieldDescriptor zzbv;
    private static final FieldDescriptor zzbw;
    private static final FieldDescriptor zzbx;
    private static final FieldDescriptor zzby;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzby zzbyVar = new zzby();
        zzbyVar.zza(1);
        zzb = builder.withProperty(zzbyVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzby zzbyVar2 = new zzby();
        zzbyVar2.zza(2);
        zzc = builder2.withProperty(zzbyVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzby zzbyVar3 = new zzby();
        zzbyVar3.zza(37);
        zzd = builder3.withProperty(zzbyVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzby zzbyVar4 = new zzby();
        zzbyVar4.zza(61);
        zze = builder4.withProperty(zzbyVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzby zzbyVar5 = new zzby();
        zzbyVar5.zza(3);
        zzf = builder5.withProperty(zzbyVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzby zzbyVar6 = new zzby();
        zzbyVar6.zza(20);
        zzg = builder6.withProperty(zzbyVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzby zzbyVar7 = new zzby();
        zzbyVar7.zza(4);
        zzh = builder7.withProperty(zzbyVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzby zzbyVar8 = new zzby();
        zzbyVar8.zza(29);
        zzi = builder8.withProperty(zzbyVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzby zzbyVar9 = new zzby();
        zzbyVar9.zza(5);
        zzj = builder9.withProperty(zzbyVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzby zzbyVar10 = new zzby();
        zzbyVar10.zza(59);
        zzk = builder10.withProperty(zzbyVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzby zzbyVar11 = new zzby();
        zzbyVar11.zza(6);
        zzl = builder11.withProperty(zzbyVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzby zzbyVar12 = new zzby();
        zzbyVar12.zza(79);
        zzm = builder12.withProperty(zzbyVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzby zzbyVar13 = new zzby();
        zzbyVar13.zza(7);
        zzn = builder13.withProperty(zzbyVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzby zzbyVar14 = new zzby();
        zzbyVar14.zza(58);
        zzo = builder14.withProperty(zzbyVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzby zzbyVar15 = new zzby();
        zzbyVar15.zza(48);
        zzp = builder15.withProperty(zzbyVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzby zzbyVar16 = new zzby();
        zzbyVar16.zza(49);
        zzq = builder16.withProperty(zzbyVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzby zzbyVar17 = new zzby();
        zzbyVar17.zza(18);
        zzr = builder17.withProperty(zzbyVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzby zzbyVar18 = new zzby();
        zzbyVar18.zza(26);
        zzs = builder18.withProperty(zzbyVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzby zzbyVar19 = new zzby();
        zzbyVar19.zza(27);
        zzt = builder19.withProperty(zzbyVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzby zzbyVar20 = new zzby();
        zzbyVar20.zza(28);
        zzu = builder20.withProperty(zzbyVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzby zzbyVar21 = new zzby();
        zzbyVar21.zza(44);
        zzv = builder21.withProperty(zzbyVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzby zzbyVar22 = new zzby();
        zzbyVar22.zza(45);
        zzw = builder22.withProperty(zzbyVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzby zzbyVar23 = new zzby();
        zzbyVar23.zza(19);
        zzx = builder23.withProperty(zzbyVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzby zzbyVar24 = new zzby();
        zzbyVar24.zza(21);
        zzy = builder24.withProperty(zzbyVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzby zzbyVar25 = new zzby();
        zzbyVar25.zza(22);
        zzz = builder25.withProperty(zzbyVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzby zzbyVar26 = new zzby();
        zzbyVar26.zza(8);
        zzA = builder26.withProperty(zzbyVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzby zzbyVar27 = new zzby();
        zzbyVar27.zza(9);
        zzB = builder27.withProperty(zzbyVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzby zzbyVar28 = new zzby();
        zzbyVar28.zza(10);
        zzC = builder28.withProperty(zzbyVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzby zzbyVar29 = new zzby();
        zzbyVar29.zza(11);
        zzD = builder29.withProperty(zzbyVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzby zzbyVar30 = new zzby();
        zzbyVar30.zza(12);
        zzE = builder30.withProperty(zzbyVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzby zzbyVar31 = new zzby();
        zzbyVar31.zza(13);
        zzF = builder31.withProperty(zzbyVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzby zzbyVar32 = new zzby();
        zzbyVar32.zza(14);
        zzG = builder32.withProperty(zzbyVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzby zzbyVar33 = new zzby();
        zzbyVar33.zza(15);
        zzH = builder33.withProperty(zzbyVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzby zzbyVar34 = new zzby();
        zzbyVar34.zza(16);
        zzI = builder34.withProperty(zzbyVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzby zzbyVar35 = new zzby();
        zzbyVar35.zza(17);
        zzJ = builder35.withProperty(zzbyVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzby zzbyVar36 = new zzby();
        zzbyVar36.zza(23);
        zzK = builder36.withProperty(zzbyVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzby zzbyVar37 = new zzby();
        zzbyVar37.zza(24);
        zzL = builder37.withProperty(zzbyVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzby zzbyVar38 = new zzby();
        zzbyVar38.zza(25);
        zzM = builder38.withProperty(zzbyVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzby zzbyVar39 = new zzby();
        zzbyVar39.zza(39);
        zzN = builder39.withProperty(zzbyVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzby zzbyVar40 = new zzby();
        zzbyVar40.zza(40);
        zzO = builder40.withProperty(zzbyVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzby zzbyVar41 = new zzby();
        zzbyVar41.zza(30);
        zzP = builder41.withProperty(zzbyVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzby zzbyVar42 = new zzby();
        zzbyVar42.zza(31);
        zzQ = builder42.withProperty(zzbyVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzby zzbyVar43 = new zzby();
        zzbyVar43.zza(32);
        zzR = builder43.withProperty(zzbyVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzby zzbyVar44 = new zzby();
        zzbyVar44.zza(33);
        zzS = builder44.withProperty(zzbyVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzby zzbyVar45 = new zzby();
        zzbyVar45.zza(34);
        zzT = builder45.withProperty(zzbyVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzby zzbyVar46 = new zzby();
        zzbyVar46.zza(35);
        zzU = builder46.withProperty(zzbyVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzby zzbyVar47 = new zzby();
        zzbyVar47.zza(36);
        zzV = builder47.withProperty(zzbyVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzby zzbyVar48 = new zzby();
        zzbyVar48.zza(46);
        zzW = builder48.withProperty(zzbyVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzby zzbyVar49 = new zzby();
        zzbyVar49.zza(47);
        zzX = builder49.withProperty(zzbyVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzby zzbyVar50 = new zzby();
        zzbyVar50.zza(69);
        zzY = builder50.withProperty(zzbyVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzby zzbyVar51 = new zzby();
        zzbyVar51.zza(42);
        zzZ = builder51.withProperty(zzbyVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzby zzbyVar52 = new zzby();
        zzbyVar52.zza(50);
        zzaa = builder52.withProperty(zzbyVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzby zzbyVar53 = new zzby();
        zzbyVar53.zza(51);
        zzab = builder53.withProperty(zzbyVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzby zzbyVar54 = new zzby();
        zzbyVar54.zza(52);
        zzac = builder54.withProperty(zzbyVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzby zzbyVar55 = new zzby();
        zzbyVar55.zza(53);
        zzad = builder55.withProperty(zzbyVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzby zzbyVar56 = new zzby();
        zzbyVar56.zza(54);
        zzae = builder56.withProperty(zzbyVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzby zzbyVar57 = new zzby();
        zzbyVar57.zza(60);
        zzaf = builder57.withProperty(zzbyVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzby zzbyVar58 = new zzby();
        zzbyVar58.zza(85);
        zzag = builder58.withProperty(zzbyVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzby zzbyVar59 = new zzby();
        zzbyVar59.zza(86);
        zzah = builder59.withProperty(zzbyVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzby zzbyVar60 = new zzby();
        zzbyVar60.zza(87);
        zzai = builder60.withProperty(zzbyVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzby zzbyVar61 = new zzby();
        zzbyVar61.zza(55);
        zzaj = builder61.withProperty(zzbyVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzby zzbyVar62 = new zzby();
        zzbyVar62.zza(56);
        zzak = builder62.withProperty(zzbyVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzby zzbyVar63 = new zzby();
        zzbyVar63.zza(57);
        zzal = builder63.withProperty(zzbyVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzby zzbyVar64 = new zzby();
        zzbyVar64.zza(62);
        zzam = builder64.withProperty(zzbyVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzby zzbyVar65 = new zzby();
        zzbyVar65.zza(63);
        zzan = builder65.withProperty(zzbyVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzby zzbyVar66 = new zzby();
        zzbyVar66.zza(64);
        zzao = builder66.withProperty(zzbyVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzby zzbyVar67 = new zzby();
        zzbyVar67.zza(65);
        zzap = builder67.withProperty(zzbyVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzby zzbyVar68 = new zzby();
        zzbyVar68.zza(66);
        zzaq = builder68.withProperty(zzbyVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzby zzbyVar69 = new zzby();
        zzbyVar69.zza(67);
        zzar = builder69.withProperty(zzbyVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzby zzbyVar70 = new zzby();
        zzbyVar70.zza(68);
        zzas = builder70.withProperty(zzbyVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzby zzbyVar71 = new zzby();
        zzbyVar71.zza(70);
        zzat = builder71.withProperty(zzbyVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzby zzbyVar72 = new zzby();
        zzbyVar72.zza(71);
        zzau = builder72.withProperty(zzbyVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzby zzbyVar73 = new zzby();
        zzbyVar73.zza(72);
        zzav = builder73.withProperty(zzbyVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzby zzbyVar74 = new zzby();
        zzbyVar74.zza(73);
        zzaw = builder74.withProperty(zzbyVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzby zzbyVar75 = new zzby();
        zzbyVar75.zza(74);
        zzax = builder75.withProperty(zzbyVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzby zzbyVar76 = new zzby();
        zzbyVar76.zza(75);
        zzay = builder76.withProperty(zzbyVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzby zzbyVar77 = new zzby();
        zzbyVar77.zza(76);
        zzaz = builder77.withProperty(zzbyVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzby zzbyVar78 = new zzby();
        zzbyVar78.zza(77);
        zzaA = builder78.withProperty(zzbyVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzby zzbyVar79 = new zzby();
        zzbyVar79.zza(78);
        zzaB = builder79.withProperty(zzbyVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzby zzbyVar80 = new zzby();
        zzbyVar80.zza(80);
        zzaC = builder80.withProperty(zzbyVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzby zzbyVar81 = new zzby();
        zzbyVar81.zza(81);
        zzaD = builder81.withProperty(zzbyVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzby zzbyVar82 = new zzby();
        zzbyVar82.zza(82);
        zzaE = builder82.withProperty(zzbyVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzby zzbyVar83 = new zzby();
        zzbyVar83.zza(83);
        zzaF = builder83.withProperty(zzbyVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzby zzbyVar84 = new zzby();
        zzbyVar84.zza(84);
        zzaG = builder84.withProperty(zzbyVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzby zzbyVar85 = new zzby();
        zzbyVar85.zza(88);
        zzaH = builder85.withProperty(zzbyVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzby zzbyVar86 = new zzby();
        zzbyVar86.zza(89);
        zzaI = builder86.withProperty(zzbyVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzby zzbyVar87 = new zzby();
        zzbyVar87.zza(90);
        zzaJ = builder87.withProperty(zzbyVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzby zzbyVar88 = new zzby();
        zzbyVar88.zza(91);
        zzaK = builder88.withProperty(zzbyVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzby zzbyVar89 = new zzby();
        zzbyVar89.zza(92);
        zzaL = builder89.withProperty(zzbyVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzby zzbyVar90 = new zzby();
        zzbyVar90.zza(93);
        zzaM = builder90.withProperty(zzbyVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzby zzbyVar91 = new zzby();
        zzbyVar91.zza(94);
        zzaN = builder91.withProperty(zzbyVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzby zzbyVar92 = new zzby();
        zzbyVar92.zza(95);
        zzaO = builder92.withProperty(zzbyVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzby zzbyVar93 = new zzby();
        zzbyVar93.zza(96);
        zzaP = builder93.withProperty(zzbyVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzby zzbyVar94 = new zzby();
        zzbyVar94.zza(97);
        zzaQ = builder94.withProperty(zzbyVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzby zzbyVar95 = new zzby();
        zzbyVar95.zza(98);
        zzaR = builder95.withProperty(zzbyVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzby zzbyVar96 = new zzby();
        zzbyVar96.zza(99);
        zzaS = builder96.withProperty(zzbyVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzby zzbyVar97 = new zzby();
        zzbyVar97.zza(100);
        zzaT = builder97.withProperty(zzbyVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzby zzbyVar98 = new zzby();
        zzbyVar98.zza(101);
        zzaU = builder98.withProperty(zzbyVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzby zzbyVar99 = new zzby();
        zzbyVar99.zza(102);
        zzaV = builder99.withProperty(zzbyVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzby zzbyVar100 = new zzby();
        zzbyVar100.zza(103);
        zzaW = builder100.withProperty(zzbyVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzby zzbyVar101 = new zzby();
        zzbyVar101.zza(104);
        zzaX = builder101.withProperty(zzbyVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzby zzbyVar102 = new zzby();
        zzbyVar102.zza(105);
        zzaY = builder102.withProperty(zzbyVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zzby zzbyVar103 = new zzby();
        zzbyVar103.zza(106);
        zzaZ = builder103.withProperty(zzbyVar103.zzb()).build();
        FieldDescriptor.Builder builder104 = FieldDescriptor.builder("lowLightAutoExposureComputationEvent");
        zzby zzbyVar104 = new zzby();
        zzbyVar104.zza(107);
        zzba = builder104.withProperty(zzbyVar104.zzb()).build();
        FieldDescriptor.Builder builder105 = FieldDescriptor.builder("lowLightFrameProcessEvent");
        zzby zzbyVar105 = new zzby();
        zzbyVar105.zza(108);
        zzbb = builder105.withProperty(zzbyVar105.zzb()).build();
        FieldDescriptor.Builder builder106 = FieldDescriptor.builder("lowLightSceneDetectionEvent");
        zzby zzbyVar106 = new zzby();
        zzbyVar106.zza(109);
        zzbc = builder106.withProperty(zzbyVar106.zzb()).build();
        FieldDescriptor.Builder builder107 = FieldDescriptor.builder("onDeviceStainRemovalLogEvent");
        zzby zzbyVar107 = new zzby();
        zzbyVar107.zza(110);
        zzbd = builder107.withProperty(zzbyVar107.zzb()).build();
        FieldDescriptor.Builder builder108 = FieldDescriptor.builder("aggregatedOnDeviceStainRemovalLogEvent");
        zzby zzbyVar108 = new zzby();
        zzbyVar108.zza(111);
        zzbe = builder108.withProperty(zzbyVar108.zzb()).build();
        FieldDescriptor.Builder builder109 = FieldDescriptor.builder("stainRemovalOptionalModuleLogEvent");
        zzby zzbyVar109 = new zzby();
        zzbyVar109.zza(PanasonicMakernoteDirectory.TAG_INTELLIGENT_RESOLUTION);
        zzbf = builder109.withProperty(zzbyVar109.zzb()).build();
        FieldDescriptor.Builder builder110 = FieldDescriptor.builder("onDeviceShadowRemovalLogEvent");
        zzby zzbyVar110 = new zzby();
        zzbyVar110.zza(113);
        zzbg = builder110.withProperty(zzbyVar110.zzb()).build();
        FieldDescriptor.Builder builder111 = FieldDescriptor.builder("aggregatedOnDeviceShadowRemovalLogEvent");
        zzby zzbyVar111 = new zzby();
        zzbyVar111.zza(114);
        zzbh = builder111.withProperty(zzbyVar111.zzb()).build();
        FieldDescriptor.Builder builder112 = FieldDescriptor.builder("shadowRemovalOptionalModuleLogEvent");
        zzby zzbyVar112 = new zzby();
        zzbyVar112.zza(115);
        zzbi = builder112.withProperty(zzbyVar112.zzb()).build();
        FieldDescriptor.Builder builder113 = FieldDescriptor.builder("onDeviceDigitalInkSegmentationLogEvent");
        zzby zzbyVar113 = new zzby();
        zzbyVar113.zza(116);
        zzbj = builder113.withProperty(zzbyVar113.zzb()).build();
        FieldDescriptor.Builder builder114 = FieldDescriptor.builder("onDeviceDocumentScannerStartLogEvent");
        zzby zzbyVar114 = new zzby();
        zzbyVar114.zza(117);
        zzbk = builder114.withProperty(zzbyVar114.zzb()).build();
        FieldDescriptor.Builder builder115 = FieldDescriptor.builder("onDeviceDocumentScannerFinishLogEvent");
        zzby zzbyVar115 = new zzby();
        zzbyVar115.zza(118);
        zzbl = builder115.withProperty(zzbyVar115.zzb()).build();
        FieldDescriptor.Builder builder116 = FieldDescriptor.builder("onDeviceDocumentScannerUiStartLogEvent");
        zzby zzbyVar116 = new zzby();
        zzbyVar116.zza(PanasonicMakernoteDirectory.TAG_BURST_SPEED);
        zzbm = builder116.withProperty(zzbyVar116.zzb()).build();
        FieldDescriptor.Builder builder117 = FieldDescriptor.builder("onDeviceDocumentScannerUiFinishLogEvent");
        zzby zzbyVar117 = new zzby();
        zzbyVar117.zza(120);
        zzbn = builder117.withProperty(zzbyVar117.zzb()).build();
        FieldDescriptor.Builder builder118 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzby zzbyVar118 = new zzby();
        zzbyVar118.zza(121);
        zzbo = builder118.withProperty(zzbyVar118.zzb()).build();
        FieldDescriptor.Builder builder119 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzby zzbyVar119 = new zzby();
        zzbyVar119.zza(122);
        zzbp = builder119.withProperty(zzbyVar119.zzb()).build();
        FieldDescriptor.Builder builder120 = FieldDescriptor.builder("onDeviceDocumentScannerUiCreateLogEvent");
        zzby zzbyVar120 = new zzby();
        zzbyVar120.zza(123);
        zzbq = builder120.withProperty(zzbyVar120.zzb()).build();
        FieldDescriptor.Builder builder121 = FieldDescriptor.builder("onDeviceSubjectSegmentationCreateLogEvent");
        zzby zzbyVar121 = new zzby();
        zzbyVar121.zza(124);
        zzbr = builder121.withProperty(zzbyVar121.zzb()).build();
        FieldDescriptor.Builder builder122 = FieldDescriptor.builder("onDeviceSubjectSegmentationLoadLogEvent");
        zzby zzbyVar122 = new zzby();
        zzbyVar122.zza(125);
        zzbs = builder122.withProperty(zzbyVar122.zzb()).build();
        FieldDescriptor.Builder builder123 = FieldDescriptor.builder("onDeviceSubjectSegmentationInferenceLogEvent");
        zzby zzbyVar123 = new zzby();
        zzbyVar123.zza(126);
        zzbt = builder123.withProperty(zzbyVar123.zzb()).build();
        FieldDescriptor.Builder builder124 = FieldDescriptor.builder("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzby zzbyVar124 = new zzby();
        zzbyVar124.zza(127);
        zzbu = builder124.withProperty(zzbyVar124.zzb()).build();
        FieldDescriptor.Builder builder125 = FieldDescriptor.builder("subjectSegmentationOptionalModuleLogEvent");
        zzby zzbyVar125 = new zzby();
        zzbyVar125.zza(128);
        zzbv = builder125.withProperty(zzbyVar125.zzb()).build();
        FieldDescriptor.Builder builder126 = FieldDescriptor.builder("documentScannerUiModuleScreenViewEvent");
        zzby zzbyVar126 = new zzby();
        zzbyVar126.zza(129);
        zzbw = builder126.withProperty(zzbyVar126.zzb()).build();
        FieldDescriptor.Builder builder127 = FieldDescriptor.builder("documentScannerUiModuleScreenClickEvent");
        zzby zzbyVar127 = new zzby();
        zzbyVar127.zza(130);
        zzbx = builder127.withProperty(zzbyVar127.zzb()).build();
        FieldDescriptor.Builder builder128 = FieldDescriptor.builder("documentScannerUiModuleScreenErrorEvent");
        zzby zzbyVar128 = new zzby();
        zzbyVar128.zza(131);
        zzby = builder128.withProperty(zzbyVar128.zzb()).build();
    }

    private zzht() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzod zzodVar = (zzod) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzodVar.zzg());
        objectEncoderContext2.add(zzc, zzodVar.zzc());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, zzodVar.zzb());
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, zzodVar.zzd());
        objectEncoderContext2.add(zzt, zzodVar.zzf());
        objectEncoderContext2.add(zzu, zzodVar.zze());
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, zzodVar.zza());
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
        objectEncoderContext2.add(zzaZ, (Object) null);
        objectEncoderContext2.add(zzba, (Object) null);
        objectEncoderContext2.add(zzbb, (Object) null);
        objectEncoderContext2.add(zzbc, (Object) null);
        objectEncoderContext2.add(zzbd, (Object) null);
        objectEncoderContext2.add(zzbe, (Object) null);
        objectEncoderContext2.add(zzbf, (Object) null);
        objectEncoderContext2.add(zzbg, (Object) null);
        objectEncoderContext2.add(zzbh, (Object) null);
        objectEncoderContext2.add(zzbi, (Object) null);
        objectEncoderContext2.add(zzbj, (Object) null);
        objectEncoderContext2.add(zzbk, (Object) null);
        objectEncoderContext2.add(zzbl, (Object) null);
        objectEncoderContext2.add(zzbm, (Object) null);
        objectEncoderContext2.add(zzbn, (Object) null);
        objectEncoderContext2.add(zzbo, (Object) null);
        objectEncoderContext2.add(zzbp, (Object) null);
        objectEncoderContext2.add(zzbq, (Object) null);
        objectEncoderContext2.add(zzbr, (Object) null);
        objectEncoderContext2.add(zzbs, (Object) null);
        objectEncoderContext2.add(zzbt, (Object) null);
        objectEncoderContext2.add(zzbu, (Object) null);
        objectEncoderContext2.add(zzbv, (Object) null);
        objectEncoderContext2.add(zzbw, (Object) null);
        objectEncoderContext2.add(zzbx, (Object) null);
        objectEncoderContext2.add(zzby, (Object) null);
    }
}
