package com.ts.coresdk.crypto.biometrcis;

/* JADX INFO: loaded from: classes5.dex */
public enum b {
    BIOMETRIC_ERROR_NO_HARDWARE,
    BIOMETRIC_ERROR_HW_UNAVAILABLE,
    BIOMETRIC_ERROR_NONE_ENROLLED,
    BIOMETRIC_ERROR_SECURITY_UPDATE_REQUIRED,
    BIOMETRIC_ERROR_UNSUPPORTED,
    BIOMETRIC_STATUS_UNKNOWN
}
