package com.google.android.gms.tapandpay;

import com.google.android.gms.common.Feature;

/* JADX INFO: loaded from: classes8.dex */
public final class zza {
    public static final Feature zzA;
    public static final Feature zzB;
    public static final Feature zzC;
    public static final Feature zzD;
    public static final Feature zzE;
    public static final Feature zzF;
    public static final Feature zzG;
    public static final Feature zzH;
    public static final Feature zzI;
    public static final Feature zzJ;
    public static final Feature zzK;
    public static final Feature zzL;
    public static final Feature zzM;
    public static final Feature zzN;
    public static final Feature zzO;
    public static final Feature zzP;
    public static final Feature zzQ;
    public static final Feature zzR;
    public static final Feature zzS;
    public static final Feature zzT;
    public static final Feature zzU;
    public static final Feature zzV;
    public static final Feature zzW;
    public static final Feature zzX;
    public static final Feature zzY;
    public static final Feature zzZ;
    public static final Feature zza;
    public static final Feature zzaa;
    public static final Feature zzab;
    public static final Feature zzac;
    public static final Feature zzad;
    public static final Feature zzae;
    public static final Feature zzaf;
    public static final Feature zzag;
    public static final Feature zzah;
    public static final Feature zzai;
    public static final Feature[] zzaj;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature zzz;

    static {
        Feature feature = new Feature("tapandpay", 1L);
        zza = feature;
        Feature feature2 = new Feature("tapandpay_account_linking", 1L);
        zzb = feature2;
        Feature feature3 = new Feature("tapandpay_add_service_listener", 1L);
        zzc = feature3;
        Feature feature4 = new Feature("tapandpay_backup_and_restore_tokenize", 1L);
        zzd = feature4;
        Feature feature5 = new Feature("tapandpay_block_payment_cards", 1L);
        zze = feature5;
        Feature feature6 = new Feature("tapandpay_check_contactless_eligibility", 1L);
        zzf = feature6;
        Feature feature7 = new Feature("tapandpay_check_notification_governance", 1L);
        zzg = feature7;
        Feature feature8 = new Feature("tapandpay_dismiss_quick_access_wallet", 1L);
        zzh = feature8;
        Feature feature9 = new Feature("tapandpay_enable_secure_keyguard", 1L);
        zzi = feature9;
        Feature feature10 = new Feature("tapandpay_felica_tos", 1L);
        zzj = feature10;
        Feature feature11 = new Feature("tapandpay_get_active_wallet_infos", 1L);
        zzk = feature11;
        Feature feature12 = new Feature("tapandpay_get_all_cards_for_account", 1L);
        zzl = feature12;
        Feature feature13 = new Feature("tapandpay_get_contactless_setup_configuration", 1L);
        zzm = feature13;
        Feature feature14 = new Feature("tapandpay_get_data_for_backup", 1L);
        zzn = feature14;
        Feature feature15 = new Feature("tapandpay_get_environment", 1L);
        zzo = feature15;
        Feature feature16 = new Feature("tapandpay_get_last_attestation_result", 1L);
        zzp = feature16;
        Feature feature17 = new Feature("tapandpay_get_quick_access_tile_status", 1L);
        zzq = feature17;
        Feature feature18 = new Feature("tapandpay_get_stable_hardware_id", 1L);
        zzr = feature18;
        Feature feature19 = new Feature("tapandpay_get_token_details", 1L);
        zzs = feature19;
        Feature feature20 = new Feature("tapandpay_get_token_status", 1L);
        zzt = feature20;
        Feature feature21 = new Feature("tapandpay_global_actions", 1L);
        zzu = feature21;
        Feature feature22 = new Feature("tapandpay_has_eligible_tokenization_target", 1L);
        zzv = feature22;
        Feature feature23 = new Feature("tapandpay_is_device_recently_unlocked", 1L);
        zzw = feature23;
        Feature feature24 = new Feature("tapandpay_issuer_api", 2L);
        zzx = feature24;
        Feature feature25 = new Feature("tapandpay_issuer_tokenize", 1L);
        zzy = feature25;
        Feature feature26 = new Feature("tapandpay_override_payment_network", 3L);
        zzz = feature26;
        Feature feature27 = new Feature("tapandpay_has_locally_cached_storage_key_available", 1L);
        zzA = feature27;
        Feature feature28 = new Feature("tapandpay_get_parental_consent_intent", 1L);
        zzB = feature28;
        Feature feature29 = new Feature("tapandpay_set_supervised_child_account_type_and_reset_onboarding_info", 1L);
        zzC = feature29;
        Feature feature30 = new Feature("tapandpay_get_is_supervised_child_wallet_user", 1L);
        zzD = feature30;
        Feature feature31 = new Feature("tapandpay_get_pending_supervised_stored_value_session", 1L);
        zzE = feature31;
        Feature feature32 = new Feature("tapandpay_perform_secure_element_management_operation", 1L);
        zzF = feature32;
        Feature feature33 = new Feature("tapandpay_perform_tokenization_operation", 1L);
        zzG = feature33;
        Feature feature34 = new Feature("tapandpay_perform_unified_tokenization_operation", 2L);
        zzH = feature34;
        Feature feature35 = new Feature("tapandpay_polling_frame_handler", 1L);
        zzI = feature35;
        Feature feature36 = new Feature("tapandpay_push_tokenize_session", 6L);
        zzJ = feature36;
        Feature feature37 = new Feature("tapandpay_push_tokenize", 1L);
        zzK = feature37;
        Feature feature38 = new Feature("tapandpay_quick_access_wallet", 1L);
        zzL = feature38;
        Feature feature39 = new Feature("tapandpay_report_unlock", 1L);
        zzM = feature39;
        Feature feature40 = new Feature("tapandpay_request_delete_token", 1L);
        zzN = feature40;
        Feature feature41 = new Feature("tapandpay_request_select_token", 1L);
        zzO = feature41;
        Feature feature42 = new Feature("tapandpay_secureelement", 1L);
        zzP = feature42;
        Feature feature43 = new Feature("tapandpay_send_wear_request_to_phone", 1L);
        zzQ = feature43;
        Feature feature44 = new Feature("tapandpay_set_data_store_environment", 1L);
        zzR = feature44;
        Feature feature45 = new Feature("tapandpay_settings", 2L);
        zzS = feature45;
        Feature feature46 = new Feature("tapandpay_screen_logging", 1L);
        zzT = feature46;
        Feature feature47 = new Feature("tapandpay_send_phone_request_to_wear", 2L);
        zzU = feature47;
        Feature feature48 = new Feature("tapandpay_show_wear_card_management_view", 1L);
        zzV = feature48;
        Feature feature49 = new Feature("tapandpay_single_user_get_active_wallet_id", 1L);
        zzW = feature49;
        Feature feature50 = new Feature("tapandpay_single_user_account_linking", 1L);
        zzX = feature50;
        Feature feature51 = new Feature("tapandpay_sync_device_info", 1L);
        zzY = feature51;
        Feature feature52 = new Feature("tapandpay_token_listing", 3L);
        zzZ = feature52;
        Feature feature53 = new Feature("tapandpay_token_listing_with_request", 1L);
        zzaa = feature53;
        Feature feature54 = new Feature("tapandpay_tokenize_account", 1L);
        zzab = feature54;
        Feature feature55 = new Feature("tapandpay_tokenize_cache", 1L);
        zzac = feature55;
        Feature feature56 = new Feature("tapandpay_tokenize_pan", 1L);
        zzad = feature56;
        Feature feature57 = new Feature("tapandpay_transmission_event", 1L);
        zzae = feature57;
        Feature feature58 = new Feature("tapandpay_wallet_feedback_psd", 1L);
        zzaf = feature58;
        Feature feature59 = new Feature("tapandpay_wallet_set_tap_doodle_enabled", 1L);
        zzag = feature59;
        Feature feature60 = new Feature("tapandpay_wallet_ui_shown_status", 1L);
        zzah = feature60;
        Feature feature61 = new Feature("tapandpay_set_receives_ineligible_card_notification", 1L);
        zzai = feature61;
        zzaj = new Feature[]{feature, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12, feature13, feature14, feature15, feature16, feature17, feature18, feature19, feature20, feature21, feature22, feature23, feature24, feature25, feature26, feature27, feature28, feature29, feature30, feature31, feature32, feature33, feature34, feature35, feature36, feature37, feature38, feature39, feature40, feature41, feature42, feature43, feature44, feature45, feature46, feature47, feature48, feature49, feature50, feature51, feature52, feature53, feature54, feature55, feature56, feature57, feature58, feature59, feature60, feature61};
    }
}
